- name: Approve PR
  if: steps.create-pr.outputs.pull-request-number
  run: |
    gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve
    echo "approved"
  env:
    GITHUB_TOKEN: ${{ env.APP_TOKEN }}

- name: Turn On PR Auto-Merge
  id: auto-merge
  if: steps.create-pr.outputs.pull-request-number
  run: >
    gh pr merge --squash --auto 
    --repo ${{ github.repository }} --delete-branch
    ${{ steps.create-pr.outputs.pull-request-number }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
