# .github/actions/approve_and_merge/action.yml
name: 'Approve and Merge PR'
description: 'Approves and merges a pull request'
inputs:
  pull-request-number:
    description: 'The pull request number'
    required: false
  app-token:
    description: 'The github app token'
    required: true
  github-token:
    description: 'The github token'
    required: true
runs:
  using: 'composite'
  steps:
    # - name: Checkout code
    #   run: actions/checkout@v2
    #   shell: bash

    - name: Approve PR
      if: inputs.pull-request-number
      run: |
        gh pr review ${{ inputs.pull-request-number }} --approve
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.APP_TOKEN }}

    - name: Turn On PR Auto-Merge
      if: inputs.pull-request-number
      run: |
        gh pr merge --squash --auto --repo ${{ github.repository }} --delete-branch ${{ inputs.pull-request-number }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
