name: Check repo secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest

    steps:
      - name: Set env as secret
        env:
          TEMP: ${{ secrets.TEMP }}
        run: |
          import os
          for q in (os.getenv("TEMP")):
            print(q)
        shell: python
