name: Check repo secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest

    steps:
      - name: Set env as secret
        env:
          TEMP_SECRET: ${{ secrets.TEMP_SECRET }}
        run: |
          import os
          print("PRINTTTTT ENV VAL NEW LINES")
          for q in (os.getenv("TEMP_SECRET")):
            print(q)
          # print("PRINTTTTT DIRECT SECRETS NEW LINES")
          # for q in (${{ secrets.TEMP_SECRET }}):
          #   print(q)
          print("PRINTTTTT ENV VAL SINGLE LINE")
          print(os.getenv("TEMP_SECRET"))
          print("PRINTTTTT DIRECT SECRET SINGLE LINE")
          print(${{ secrets.TEMP_SECRET }})
        shell: python
