#
name: Check repo secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest

    steps:
      - name: Set env as secret
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          import os
          for q in (os.getenv("TEST")):
            print(q)
        shell: python
