name: Check repo secrets

on:
  workflow_dispatch:

jobs:
  check_secrets:
    name: Check secrets
    runs-on: ubuntu-latest

    steps:
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.TEMP_SECRET }}
        run: |
          import os
          print("PRINTTTTT")
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python
