name: Code coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  coverage:
    name: Create PR comment
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v3
        
      - name: Create comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            try {
            const filePath = 'code-coverage.html'
            const content = fs.readFileSync(filePath, 'utf8')
            const result = await github.rest.issues.createComment({
              issue_number: context.repo_owner,
              repo: context.repo.repo
              body: content
              })
              console.log(result)
            } catch (error) {
              console.error('error')
            }
