name: Code coverage

on: 
  workflow_dispatch:
    branches:
      - main
      
jobs:
  code-coverage:
    name: unit tests coverage
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: run tests
        id: report-files
        run: |
          chmod +x gradlew
          ./gradlew debugCoverage --continue
          {
            echo 'file_paths<<EOF'
            find . -type f -and -path '*build/reports/jacoco/debugCoverage/html/index.html' 
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: gen report
        run: |
          chmod +x ./.github/scripts/code_coverage.py
          table_string=$(python3 ./.github/scripts/code_coverage.py "${{ steps.report-files.outputs.file_paths}}")
          echo "$table_string" >> $GITHUB_STEP_SUMMARY
