name: Create graph

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Matplotlib if not already installed
        run: |
          if ! pip show matplotlib >/dev/null 2>&1; then
              pip install matplotlib
          fi

      - name: Create graph
        id: create-graph
        run: |
          chmod +x ./.github/scripts/graph.py
          python3 ./.github/scripts/graph.py
          cat .github/scripts/plot.png

      - name: find graph
        run: |
          find . -type f -and -path '*/plot.png'

        
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload graph
          path: ./github/scripts/plot.png

      # - name: Create, Approve and Merge PR
      #   uses: ./.github/actions/create_approve_and_merge
      #   with:
      #     title: 'Update graph'
      #     commit-message: "Commit message 123"
      #     create-pr-app-id: ${{ secrets.APP_ID }}
      #     create-pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      #     approve-pr-app-id: ${{ secrets.ALTERNATE_APP_ID }}
      #     approve-pr-app-private-key: ${{ secrets.ALTERNATE_APP_PRIVATE_KEY }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
