name: Hitesh workflow

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

env:
  COMMIT_MESSAGE: |
    Update Baseline Profile

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    ACLOVERRIDE CODEOWNEROVERRIDE CUSTOMVALIDATIONSOVERRIDE

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    
    steps:

      - name: Checkout Repository1
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: DODO
        run: |
          git show
          git diff

      - name: Checkout Repository
        uses: actions/checkout@v2
          

      - name: Jojo version
        run: |
          git rev-list HEAD --count
          git rev-list -n 5 origin/main -- gradle.properties
          commit_hashes=$(git rev-list -n 5 origin/main -- gradle.properties)
          echo "Commit hashes: $commit_hashes"
 
