name: Hitesh workflow

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

env:
  COMMIT_MESSAGE: |
    Update Baseline Profile

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    ACLOVERRIDE CODEOWNEROVERRIDE CUSTOMVALIDATIONSOVERRIDE

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Jojo version
        run: |
          git show
          diff_po=$(git show)
          echo "diff $diff_jo"

      - name: Gojo version
        run: |
          git log -3
          diff_po=$(git log -3)
          echo "diff $diff_jo"

      - name: Bojo version
        run: |
          echo "bojo {{github.event.pull_request.head.sha}}"

      - name: Optimus
        run: |
          git diff
          diff_po=$(git diff)
          echo "diff $diff_jo"
 
