name: Measure coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew debugCoverage

      - name: my-app-install token
        id: my-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ALTERNATE_APP_ID }}
          private-key: ${{ secrets.ALTERNATE_APP_PRIVATE_KEY }}

      - name: print app token
        run: |
          echo "APP_TOKEN=${{ steps.my-app.outputs.token }}" >> $GITHUB_ENV

      # generates coverage-report.md and publishes as checkrun
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9
        with:
          coverage_results_path: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
      
      # Publish Coverage Job percent  # Optional
      - name: Add Coverage Job percent
        run: |
          echo "percent : ${{ steps.jacoco_reporter.outputs.coverage_percentage }}"
