name: Measure coverage

on:
  push:
    branches:
      - main 
  pull_request:

env:
  COMMIT_MESSAGE: |
    Update jacoco badge

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew debugCoverage --continue

      - name: print csv files
        id: csv_files
        run: |
          original_string=$(find . -type f -name "debugCoverage.csv" \( -path "*app*" -o -path "*paymentGateway*" \))
          modified_string=$(echo "$original_string" | tr ' ' '\n')
          echo "CSV=$modified_string" >> $GITHUB_ENV

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: >
            ${{ env.CSV }}

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"


      - name: my-app-install token
        id: my-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ALTERNATE_APP_ID }}
          private-key: ${{ secrets.ALTERNATE_APP_PRIVATE_KEY }}

      - name: print app token
        run: |
          echo "APP_TOKEN=${{ steps.my-app.outputs.token }}" >> $GITHUB_ENV

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: github-actions/readme-update
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@linkedin.com>
          title: 'Update readme'
          body: ${{ env.COMMIT_MESSAGE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            */jacoco.svg
            
      - name: pr number
        run: | 
          echo "pr number : ${{ steps.create-pr.outputs.pull-request-number }}"

      - name: Run script
        run: |
          chmod +x ./.github/approve_and_merge_pr.sh ${{ steps.create-pr.outputs.pull-request-number }} ${{ env.APP_TOKEN }} ${{ secrets.GITHUB_TOKEN }}
          

      # - name: Approve PR
      #   if: steps.create-pr.outputs.pull-request-number
      #   run: |
      #      gh pr review ${{ steps.create-pr.outputs.pull-request-number }} --approve
      #      echo "approved"
      #   env:
      #      GITHUB_TOKEN: ${{ env.APP_TOKEN }}

      # - name: Turn On PR Auto-Merge
      #   id: auto-merge
      #   if: steps.create-pr.outputs.pull-request-number
      #   run: >
      #     gh pr merge --squash --auto 
      #     --repo ${{ github.repository }} --delete-branch
      #     ${{ steps.create-pr.outputs.pull-request-number }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
