name: Measure coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew debugCoverage

      - name: trigger workflow
        if: github.event.pull_request.merged == true
        run: |
          echo "triggered the workflow"

      - name: my-app-install token
        id: my-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ALTERNATE_APP_ID }}
          private-key: ${{ secrets.ALTERNATE_APP_PRIVATE_KEY }}

      - name: print app token
        run: |
          echo "APP_TOKEN=${{ steps.my-app.outputs.token }}" >> $GITHUB_ENV

      - name: test
        uses: kevinfjiang/coverage-badge@v1
        with:
          coverage: 64
          change_file: ./README.md
          repo_token: ${{ env.APP_TOKEN }}
