name: Measure coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Module Coverage
        run: ./gradlew debugCoverage

      - name: trigger workflow
        if: github.event.pull_request.merged == true
        run: |
          echo "triggered the workflow"

      - name: my-app-install token
        id: my-app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ALTERNATE_APP_ID }}
          private-key: ${{ secrets.ALTERNATE_APP_PRIVATE_KEY }}

      - name: print app token
        run: |
          echo "APP_TOKEN=${{ steps.my-app.outputs.token }}" >> $GITHUB_ENV

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file:  |
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
