#  Copyright 2019 Foo. All rights reserved. MIT license.
name: Check license

on: 
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get json
        run: |
          content=$(cat .licenserc.json)
          echo "content: $content"

          # Read the JSON content
          # Initialize an empty array to store the keys
          keys=()

          # Extract keys from the JSON object and append them to the array
          while IFS= read -r key; do
            keys+=("$key")
          done < <(jq -r 'keys | .[]' <<< "$content")

          # Print the keys
          printf '%s\n' "${keys[@]}"

          # find . -type f -name '*.java'
          # # find . -type f -name '*.java' -exec grep -F -q "$key1_value" {} \; -print
          # find . -type f -name '*.yml'
          # # find . -type f -name '*.yml' -exec grep -qF "$key2_value" {} \; -exec echo "✅ {}" \; -o -exec echo "❌ {}" \;
          # # find . -type f -name '*.yml' -exec grep -qF "$key2_value" {} \; -printf "✅ %p\n" -o -printf "❌ %p\n"

          # Iterate over each .yml file and check for the presence of key2_value
          for key in "${keys[@]}"; do
            files=$(find . -type f -name "$key")
            value=$(echo "$content" | jq -r --arg key "$key" '.[$key]')
            for file in $files; do
              if grep -qF "$value" "$file"; then
                echo "$file ✅"
              else
                echo "$file ❌"
              fi
            done
          done
        shell: bash
