#  Copyright 2019 Foo. All rights reserved. MIT license.
name: Check license

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - '*'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get json
        run: |
          content=$(cat .licenserc.json)
          echo "content: $content"
          
          # Extract specific key-value pairs using jq
          key1_value=$(echo "$content" | jq -r '."**/*.java"')
          key2_value=$(echo "$content" | jq -r '."**/*.yml"')

          # Print the extracted values
          echo "Key1 value: $key1_value"
          echo "Key2 value: $key2_value"
          
          # Extract keys from the JSON object
          keys=$(jq -r 'keys | .[]' <<< "$content")

          # Print the extracted keys
          echo "Keys: $keys"

          find . -type f -name '*.java'
          # find . -type f -name '*.java' -exec grep -F -q "$key1_value" {} \; -print
          find . -type f -name '*.yml'
          # find . -type f -name '*.yml' -exec grep -qF "$key2_value" {} \; -exec echo "✅ {}" \; -o -exec echo "❌ {}" \;
          # find . -type f -name '*.yml' -exec grep -qF "$key2_value" {} \; -printf "✅ %p\n" -o -printf "❌ %p\n"

          # Iterate over each .yml file and check for the presence of key2_value
          for key in $keys; do
            echo "key: $key"
            files=$(find . -type f -name "$key")
            echo "files: $files"
            echo "getKey: '."$key"' "
            escaped_key=$(sed 's/[*]/\\*/g' <<< "$key")  # Escape wildcard characters
            echo "escaped key: $escaped_key"
            value=$(echo "$content" | jq -r --arg file_pattern "$escaped_key" ".$escaped_key")
            echo "value: $value"
            for file in $files; do
              if grep -qF "$value" "$file"; then
                echo "$file ✅"
              else
                echo "$file ❌"
              fi
            done
          done

          # for key in $keys; do
          #   echo "key: $key"
          #   files=$(find . -type f -name "$key")
          #   echo "files: $files"
          #   value=$(echo "$content" | jq -r ".$key")
          #   echo "value: $value"
          #   for file in $files; do
          #     if grep -qF "$value" "$file"; then
          #       echo "$file ✅"
          #     else
          #       echo "$file ❌"
          #     fi
          #   done
          # done
        shell: bash
