#  Copyright 2019 Foo. All rights reserved. MIT license.
name: Check license

on: 
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get json
        run: |
          content=$(cat .licenserc.json)
          echo "content: $content"

          # Read the JSON content
          
          # Initialize an empty array to store the keys
          keys=()

          # Extract keys from the JSON object and append them to the array
          while IFS= read -r key; do
            keys+=("$key")
          done < <(jq -r 'keys | .[]' <<< "$content")

          # Print the keys
          printf '%s\n' "${keys[@]}"

          # Iterate over each .yml file and check for the presence of key2_value
          for key in "${keys[@]}"; do
            files=$(find . -type f -name "$key")
            value=$(echo "$content" | jq -r --arg key "$key" '.[$key]')
            for file in $files; do
              if grep -qF "$value" "$file"; then
                echo "$file ✅"
              else
                echo "$file ❌"
              fi
            done
          done
        shell: bash
