#  Copyright 2019 Foo. All rights reserved. MIT license.
name: Check license

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get json
        run: |
          content=`cat .licenserc.json`
          echo "content: $content"
          
          # Extract specific key-value pairs using jq
          key1_value=$(echo "$content" | jq -r '."**/*.java"')
          key2_value=$(echo "$content" | jq -r '."**/*.yml"')
          
          # Print the extracted values
          echo "Key1 value: $key1_value"
          echo "Key2 value: $key2_value"

          find . -type f -name '*.java'
          find . -type f -name '*.java' -exec grep -q "$key1_value" {} \; -print
          find . -type f -name '*.yml'
          find . -type f -name '*.yml' -exec grep -q "$key2_value" {} \; -print

      # - name: find certificate
      #   run: |
      #     find . -type f -name '*.java'
      #     find . -type f -name '*.java' -exec grep -q $key1_value {} \; -print
      #     find . -type f -name '*.yml'
      #     find . -type f -name '*.yml' -exec grep -q $key2_value {} \; -print

        
      # - name: upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: upload graph
      #     path: ./.github/scripts/plot.png
