name: license check

on: 
  push:
    branches:
      - '*'
  pull_request:
      
jobs:
  license-check:
    name: license check
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: license check
        uses: kt3k/license_checker_github_action@v1.0.6
