#  Copyright 2019 Foo. All rights reserved. MIT license.
name: Check license

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: get json
        run: |
          content=`cat .licenserc.json`
          echo "content: $content"
          
          # Extract specific key-value pairs using jq
          key1_value=$(echo "$content" | jq -r '."**/*.java"')
          key2_value=$(echo "$content" | jq -r '."**/*.yml"')
          
          # Print the extracted values
          echo "Key1 value: $key1_value"
          echo "Key2 value: $key2_value"

          # find . -type f -name '*.java'
          find . -type f -name '*.java' -exec grep -F -q "$key1_value" {} \; -print
          # find . -type f -name '*.yml'
          # find . -type f -name '*.yml' -exec grep -qF "$key2_value" {} \; -exec echo "✅ {}" \; -o -exec echo "❌ {}" \;
          # find . -type f -name '*.yml' -exec grep -qF "$key2_value" {} \; -printf "✅ %p\n" -o -printf "❌ %p\n"

          # Store the list of .yml files in a variable
          java_files=$(find . -type f -name '*.java')
          yml_files=$(find . -type f -name '*.yml')

          # Iterate over each .yml file and check for the presence of key2_value
          for file in $java_files; do
            if grep -qF "$key1_value" "$file"; then
              echo "$file ✅"
            else
              echo "$file ❌"
            fi
          done
          for file in $yml_files; do
            if grep -qF "$key2_value" "$file"; then
              echo "$file ✅"
            else
              echo "$file ❌"
            fi
          done
        shell: bash
