name: My test workflow

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Set up Java
       uses: actions/setup-java@v2
       with:
          distribution: 'adopt'
          java-version: '11'

     - name: Read Version Number
       id: version
       run: |
            version=$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
            echo "VERSION: $version"

     - name: Update README Badge
       run: |
            sed -i 's/\(badge\/version-v[0-9]\+\(\.[0-9]\+\)-blue\.svg)/badge\/version-v${{ steps.version.outputs.VERSION }}-blue.svg/' README.md
            cat README.md  # Print README content for debugging




