name: my test name changed

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: push code
        run: echo "code pushed"

      - name: Save Workflow Status to JSON
        run: |
          echo '{"status": "$STATUS"}' >> workflow_status.json

      - name: Display Workflow Status
        run: |
          cat workflow_status.json
