name: my test workflow updated twice

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: push code
        run: echo "code pushed"
