name: my test name changed

on:
  push:
    branches:
      - main
  # pull_request:
  #   paths-ignore: "**/*.md"
  
jobs:
  testing:
    runs-on: ubuntu-latest
    

    steps:
      - name: Delay for 5 minutes
        run: |
          echo "Sleeping for 10 seconds..."
          sleep 10
          echo "Done sleeping."
        
      - name: push code
        run: echo "code pushed"

      - name: Set Workflow Status
        run: |
          if [ $? -eq 0 ]; then
            echo "STATUS=Passed" >> $GITHUB_ENV
            echo "::set-output name=status::Passed"
          else
            echo "STATUS=Failed" >> $GITHUB_ENV
            echo "::set-output name=status::Failed"
          fi

      - name: Save Workflow Status to JSON
        run: >
          echo '{"status": "$STATUS"}' >> workflow_status.json

      - name: Upload Workflow Status JSON as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow-status
          path: workflow_status.json
