name: Performance Profiling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  internal_memory_usage_calculate:
    name: Internal Memory Usage
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout PR base branch
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.base_ref }}
          
      # - name: on base branch
      #   id: on_base_branch
      #   uses: ./.github/actions/composit

      # - name: akhil
      #   run: |
      #     echo "::set-output name=on_base_branch::${{ steps.on_base_branch.outputs.abc }}"
      #     echo "${{ steps.on_base_branch.outputs.abc }}"
          
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: on current branch
        id: on_current_branch
        uses: ./.github/actions/composit

      - name: reddy
        run: |
          echo "::set-output name=on_current_branch::${{ steps.on_current_branch.outputs.abc }}"
          echo "${{ steps.on_current_branch.outputs.abc }}"
