name: Performance Profiling

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  internal_memory_usage_calculate:
    name: Internal Memory Usage
    runs-on: ubuntu-latest

    steps:
          
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Start emulator
        id: internal_memory
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          script: |
            chmod +x ./.github/scripts/internal.sh
            chmod +x gradlew
            ./gradlew installDebug
            ./.github/scripts/internal.sh
            # internal_memory=$(./adb shell df)
            # echo $internal_memory
            # internal_memory2=$(./adb shell df -h | grep /dev/fuse)
            # echo $internal_memory2

      
