name: Scheduled execution of all tests
on:
  push:
    branches:
      VaibhavSMisal-patch-2
  pull_request:
    branches:
      VaibhavSMisal-patch-2
  # schedule:
  #   - cron: '15 14 * * *'
  workflow_dispatch:

jobs:
  scheduled_execution_of_all_tests:
    name: Scheduled execution of all tests and sending results on Slack 
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: run all unit tests and save the output
        id: unitTests
        run: |
          chmod +x gradlew
          ./gradlew test --continue > unit_tests_output.txt || true

      - name: print unit tests output
        if: always()
        run: cat unit_tests_output.txt

      - name: Create and Launch emulator
        uses: ./.github/actions/launch_emulator
        with:
          script: |
            adb devices

      - name: Run all instrumented tests and save the output
        id: instrumentedTests
        run: ./gradlew connectedCheck > instrumented_tests_output.txt

      - name: print instrumented tests output
        if: always()
        run: cat instrumented_tests_output.txt

      - name: send message over Slack
        run: |
          if [ ${{ steps.unitTests.outcome }} == 'success' && ${{ steps.instrumentedTests.outcome }} == 'success']; then
            echo "All tests passed!"
            # curl -X POST -H 'Content-type: application/json' --data '{"message" : "All tests passed!"}' $SLACK_WEBHOOK_URL
          else
            unit_tests=$(cat unit_tests_output.txt | grep -E "com.example.breach.*FAILED")
            instrumented_tests=$(cat instrumented_tests_output.txt | grep -E "com.example.breach.*FAILED")
            echo "Following unit tests failed!\n $unit_tests"
            echo "Following instrumented tests failed!\n $instrumented_tests"
            # curl -X POST -H 'Content-type: application/json' --data '{"message" : "Following unit tests failed!\n $unit_tests"}' $SLACK_WEBHOOK_URL
          fi
        # env:
        #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: send message
      #   if: always()
      #   run: |
      #     if [ ${{ steps.ranTest.outcome }} == 'success' ]; then
      #       echo "All tests passed!"
      #     else
      #       tests=$(cat test_output.txt | grep -E "com.example.breach.*FAILED")
      #       echo "Following tests failed!\n $tests"
      #     fi
