name: Send slack message

on: 
  schedule:
    - cron: '15 14 * * *'
  workflow_dispatch:
  
      
jobs:
  license-check:
    name: send slack message
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: run tests
        id: test
        run: |
          chmod +x gradlew
          ./gradlew test --continue > test_output.txt
        shell: bash

      - name: print output
        if: always()
        run: cat test_output.txt | grep -E "com.example.breach.*FAILED"
        shell: bash

      - name: print date
        if: always()
        run: |
          today=$(date +'%Y-%m-%d')
          echo "today: $today"
        shell: bash

      # - name: send message
      #   if: always()
      #   run: |
      #     if [ ${{ steps.test.outcome }} == 'success' ]; then
      #       curl -X POST -H 'Content-type: application/json' --data '{"message" : "All tests passed!"}' $SLACK_WEBHOOK_URL
      #     else
      #       tests=$(cat test_output.txt | grep -E "com.example.breach.*FAILED")
      #       curl -X POST -H 'Content-type: application/json' --data '{"message" : "Following tests failed!\n $tests"}' $SLACK_WEBHOOK_URL
      #     fi
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   shell: bash
          
