name: Mvgergvbryebreb

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

env:
  COMMIT_MESSAGE: |
    Update Baseline Profile

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    ACLOVERRIDE CODEOWNEROVERRIDE CUSTOMVALIDATIONSOVERRIDE

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{  github.head_ref }}
          fetch-depth: 0

      - name: Get previous version
        id: get-previous-version
        run: |
          commit_hashes=$(git rev-list -n 2 origin/main -- gradle.properties)
          echo "Commit hashes: $commit_hashes"
    
          second_last_commit_hash=$(echo "$commit_hashes" | tail -n 1)
          echo "Second-to-last commit hash: $second_last_commit_hash"
    
          previous_version=$(git show $second_last_commit_hash:gradle.properties | grep '^version' | cut -d= -f2 | tr -d '[:space:]')
          echo "data: $(git show $second_last_commit_hash:gradle.properties)"
          echo "Previous version: $previous_version"
          echo "::set-output name=prev_version::$previous_version"

      - name: Get current version
        id: get-current-version
        run: |
          echo "::set-output name=current_version::$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')"

      - name: Check for version change
        run: |
          echo "Previous version: ${{ steps.get-previous-version.outputs.prev_version }}"
          echo "Current version: ${{ steps.get-current-version.outputs.current_version }}"
          if [ "${{ steps.get-previous-version.outputs.prev_version }}" = "${{ steps.get-current-version.outputs.current_version }}" ]; then
            echo "No version change. Exiting workflow."
            echo "::set-env name=SKIP_NEXT_STEPS::true"
          fi

      - name: Update README Badge
        if: env.SKIP_NEXT_STEPS != 'true'
        run: |
          version=$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
          version=$(echo "$version" | sed 's/-/%E2%80%90/g')
          echo "$version"
          sed -i "s/\(badge\/version-v.*-blue\.svg\)/badge\/version-v$version-blue.svg/" README.md
          cat README.md

      - name: Create PR
        if: env.SKIP_NEXT_STEPS != 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: github-actions/readme-update
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@linkedin.com>
          title: 'Update readme'
          body: ${{ env.COMMIT_MESSAGE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?head=github-actions/readme-update" \
          | jq -r '.[0].number')

          curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge"

          echo "Pull request merged!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Turn On PR Auto-Merge
      #   if: env.SKIP_NEXT_STEPS != 'true'
      #   run: >
      #     gh pr merge --squash --auto
      #     --repo ${{ github.repository }}
      #     ${{ steps.create-pr.outputs.pull-request-number }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch
        if: env.SKIP_NEXT_STEPS != 'true'
        run: |
          git push origin --delete github-actions/readme-update
