name: Mvgergvbryebreb

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

env:
  COMMIT_MESSAGE: |
    Update Baseline Profile

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    ACLOVERRIDE CODEOWNEROVERRIDE CUSTOMVALIDATIONSOVERRIDE

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{  github.head_ref }}
          fetch-depth: 0

      - name: Get previous version
        id: get-previous-version
        run: |
          commit_hashes=$(git rev-list -n 2 origin/main -- gradle.properties)
          second_last_commit_hash=$(echo "$commit_hashes" | tail -n 1)
          previous_version=$(git show $second_last_commit_hash:gradle.properties | grep '^version' | cut -d= -f2 | tr -d '[:space:]')
          previous_line=$(git show $second_last_commit_hash:gradle.properties | grep -n '^version' | cut -d ":" -f1)
          echo "::set-output name=prev_version::$previous_version"
          echo "::set-output name=prev_line::$previous_line"

      - name: Get current version
        id: get-current-version
        run: |
          echo "::set-output name=current_version::$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')"
          echo "::set-output name=current_line::$(grep -n '^version' gradle.properties | cut -d ":" -f1)"

      - name: Check for version change
        run: |
          if [ "${{ steps.get-previous-version.outputs.prev_version }}" = "${{ steps.get-current-version.outputs.current_version }}" ]; then
            echo "No version change. Exiting workflow."
            echo "SKIP_NEXT_STEPS=true" >> $GITHUB_ENV
          fi

          if [ "${{ steps.get-previous-version.outputs.prev_line }}" = "${{ steps.get-current-version.outputs.current_line }}" ]; then
            echo "No line change.
            echo "LINE_NOT_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Update README Badge
        if: env.SKIP_NEXT_STEPS != 'true'
        run: |
          version=$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
          current_line = $(grep -n '^version' gradle.properties | cut -d ":" -f1)
          version=$(echo "$version" | sed 's/-/%E2%80%90/g')
          echo "$version"
          sed -i "s/\(badge\/version-v.*-blue\.svg\)/badge\/version-v$version-blue.svg/" README.md
          if [env.LINE_NOT_CHANGED != 'true']; then
            sed -i "s/\(badge\/version-v[^-]*-blue\.svg[^#]*#L\)[0-9]\+/\1${current_line}/" README.md
          cat README.md

      - name: Create PR
        if: env.SKIP_NEXT_STEPS != 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: github-actions/readme-update
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@linkedin.com>
          title: 'Update readme'
          body: ${{ env.COMMIT_MESSAGE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Turn On PR Auto-Merge
        if: env.SKIP_NEXT_STEPS != 'true'
        run: >
          gh pr merge --squash --auto
          --repo ${{ github.repository }}
          ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch
        if: env.SKIP_NEXT_STEPS != 'true'
        run: |
          git push origin --delete github-actions/readme-update
